apiVersion: apps/v1
kind: Deployment
metadata:
  name: minha-app-deployment
spec:
  replicas: 2 # Estado desejado: 2 pods rodando, escalabilidade
  selector:
    matchLabels:
      app: minha-app-node #imagem docker
  template:
    metadata:
      labels:
        app: minha-app-node
    spec:
      containers:
      - name: minha-app-container
        image: minha-app-node:v1 # A imagem que construímos
        ports:
        - containerPort: 3000
        # imagePullPolicy: Never # Use isso se o K8s não encontrar a imagem local do Minikube
