version: '3.8'

services:
  app:
    build: .
    ports:
      # Mapeia a porta da máquina para a variável dentro do container
      - "${APP_PORT}:${APP_PORT}"
    # Carrega as variáveis do arquivo .env para dentro deste serviço
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    # O container do Postgres espera variáveis com nomes específicos.
    # Aqui, nós lemos as variáveis do nosso .env e as atribuímos
    # aos nomes que o Postgres espera (ex: POSTGRES_USER).
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: